import type { Metadata } from "next";
import {ReactNode} from "react";
import {AppSidebar} from "@/src/app/components/sidebar/AppSidebar";
import {SidebarProvider, SidebarTrigger} from "@/components/ui/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
      <SidebarProvider>
        <AppSidebar />
          <header className="flex h-14 items-center gap-2 px-4 md:hidden">
              <SidebarTrigger className="text-deep-plum hover:text-graphite-text" />
          </header>
          <main className="flex-1 min-w-0">
              {children}
          </main>
      </SidebarProvider>
  );
}
