import type { Metadata } from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {ClerkProvider} from "@clerk/nextjs";
import {ReactNode} from "react";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.className} h-full antialiased`}
    >
      <body className="bg-white min-h-full flex flex-col items-center justify-center">
      <ClerkProvider pub waitlistUrl="/waitlist" afterSignOutUrl="/auth/login">
        {children}
      </ClerkProvider>
      </body>
    </html>
  );
}
