import type { Metadata } from "next";
import "./globals.css";
import {ReactNode} from "react";
import {inter, playfairDisplay} from "@/src/fonts";
import {UserButton} from "@/src/UserButton";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.className} ${playfairDisplay.className} h-full antialiased`}
    >
      <body className="bg-white min-h-full flex flex-col items-center justify-center">
      {children}
      </body>
    </html>
  );
}
