import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {ClerkProvider, Show, SignInButton, SignUpButton, UserButton} from "@clerk/nextjs";
import {ReactNode} from "react";
import {shadcn} from "@clerk/ui/themes";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="bg-white min-h-full flex flex-col items-center justify-center">
      <ClerkProvider appearance={{
        theme: shadcn,
        options: {
          socialButtonsPlacement: "bottom",
          unsafe_disableDevelopmentModeWarnings: true
        }
      }}>
        <header className="flex justify-end items-center p-4 gap-4 h-16">
          <Show when="signed-out">
            <SignInButton>
              <Link href="/auth/login" className="bg-yellow-200 border p-4 rounded-full">Sign In</Link>
            </SignInButton>
            <SignUpButton>
              <Link href="/auth/signup" className="bg-yellow-200 border p-4 rounded-full">Sign Up</Link>
            </SignUpButton>
          </Show>
          <Show when="signed-in">
            HDHSDHSHD hih
            <UserButton />
          </Show>
        </header>
        {children}
      </ClerkProvider>
      </body>
    </html>
  );
}
